# Nginx configuration file

worker_processes 1;  # Número de procesos de trabajo

# Sección events (obligatoria)
events {
    worker_connections 1024;  # Número máximo de conexiones por trabajador
}

# Sección http (donde se configuran los servidores backend y balanceo de carga)
http {
    upstream backend_servers {
        server localhost:3000;  # Server1 en el puerto 3000
        server localhost:3001;  # Server2 en el puerto 3001
    }

    server {
        listen 80;  # El servidor escucha en el puerto 80 (HTTP)

        # Redirige todas las solicitudes al grupo de servidores backend (balanceo de carga)
        location / {
            proxy_pass http://backend_servers;  # Redirige al grupo de servidores backend
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Redirige las solicitudes específicas hacia Backend 1
        location /backend-1/ {
            proxy_pass http://localhost:3000/;  # Redirige a Backend 1
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Redirige las solicitudes específicas hacia Backend 2
        location /backend-2/ {
            proxy_pass http://localhost:3001/;  # Redirige a Backend 2
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
